Tarefa 4 - MPL 4x3x2

A seguir, você implementará uma rede 4x3x2 orientada a frente, com funções de ativação sigmóide em ambas as
camadas.

Coisas a fazer:

● Calcular o input da camada oculta.

● Calcular o output da camada oculta.

● Calcular o input da camada de output.

● Calcular o output da rede.

In [20]:
import numpy as np
sigmoid = lambda x: 1/(1 + np.exp(-x))

inputs_ = np.array([0.1,0.3,0.5,0.2])
# tamanho: n_inputs é implícito
# 4x3x2
size = [len(inputs_),3,2] #camada interna e de saída eu decido
sigmoid_prime = lambda x: x * (1 - x) #poupando recursos entra somente o output pois já calculou-se o sigmoid

Suvenier rsrsrs:

In [21]:

class barrinha:
    def __init__(self,total):
        self.total = total -1
        self.value = 0
        self.foo = str("["+"="*50+"]")
        self.bar = str("["+"-"*50+"]")
    def __str__(self):
        pc = self.value/self.total
        pcst = str(int(pc*100))
        return self.foo[:1+int(pc*50)] +pcst+"%---"[:-len(pcst)]+ self.bar[1+int(pc*50):]
    def refresh(self, value):
        self.value = value

        
t = 11
b = barrinha(t)
for i in range(t):
    b.refresh(i)
    print(b)

[0%----------------------------------------------------]
[=====10%----------------------------------------------]
[==========20%-----------------------------------------]
[===============30%------------------------------------]
[====================40%-------------------------------]
[=========================50%--------------------------]
[==============================60%---------------------]
[===================================70%----------------]
[========================================80%-----------]
[=============================================90%------]
[==================================================100%]


Espero conseguir fazer uma rede neural totalmente flexível em relação ao seu tamanho:

In [36]:
weights = [np.random.normal(scale=inp**-.5, size=(inp,h)) for inp,h in zip(size,size[1:]) ]
originais = weights
bias = 0
weights

[array([[ 0.90955775, -0.07822893, -0.46308702],
        [-0.08293978, -0.31934742,  0.92072971],
        [-0.51589327,  0.65452288, -0.27600599],
        [-0.03753413, -0.40289662, -0.02308366]]),
 array([[-1.09021127,  0.78569208],
        [-0.98302725,  0.11217452],
        [ 0.0417356 , -0.55411284]])]

In [23]:



#for it in range(0,100): #100 ciclos a princípio
def foward(): #apenas 1 ciclo para a questão numero 4
    for camada in range(0,len(size) - 1):
        h = np.dot(wires[camada], weights[camada]) #multiplica peso e entrada e faz o somatório
        output = sigmoid(h)
        #error_term[camada+1] = np.zeros((len(output), size[camada+1]))
        wires[camada+1] = output
        print ("="*camada+">camada:{}\ninput: {}\noutput: {}".format(camada,wires[camada],output))

        grads[camada]=sigmoid_prime(output)
        print("gradiente: {}".format(grads[camada]))
    yield foward()
     #   error_term = erro * output_grad
     #   print ("error term: {}".format(error_term))
      #  dw[camada] += [x*error_term for x in inputs[camada]] #Atualiza o passo! lista do np para isso funcionar
      #  weights +=  [learnrate * w / it for w in dw] #atulizar pesos
      #  print ("passo: {}, pesos: {}\n".format(dw,weights))
      #  erro_m = erro**2/it

dw: [matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), matrix([[0., 0.],
        [0., 0.],
        [0., 0.]])]
wires: [array([0.1, 0.3, 0.5, 0.2]), 0, 0]


BackTracking:

In [40]:
def backward(epoch):
    print("\nBack Propagation:")
    camada = -1 #última da lista de camadas
    print("="*(len(size)-1+camada)+">camada {}\ninput : {}\noutput: {}".format(camada + len(size)-1, wires[camada-1],wires[camada]))
    erro = y - wires[camada]
    print("erro saída: {}".format(erro))
#    print("inputs outputs: {}\n".format(wires))
#    print("grads: \n{}".format(grads[camada-1] ) )
#    print("weigths: \n{}".format(weights[camada] ) )   
#     print("error_term: \n{}".format(error_term ) )
#     print("grads * weights: \n{}".format( (error_term[camada]* weights[camada]).T * grads[camada-1] ) )
    error_term[camada] = erro * grads[camada] # err camada de saída * f'
#     print("error_term: \n{}".format(error_term))
    print("err_term: \n{}\npesos: \n{}\ngradiente: \n{}\n".format(error_term[camada], weights[camada], grads[camada]))



#     print("erro: \n{}".format(erro))
#     print("error_term: \n{}".format(error_term))
#     print("pesos: \n{}".format(weights[camada]))
    
#     print("incremento delta: \n{}\ndw shape:{}".format([error_term[camada] * x for x in wires[camada-1]],dw[camada]))
    dw[camada] += np.matrix([error_term[camada] * x for x in wires[camada-1]]) #Atualiza o passo! lista do np para isso funcionar
#    weights[camada] +=  [learnrate * w / epoch for w in dw[camada]] #atulizar pesos
#    weights[camada] +=  [learnrate * w / epoch for w in dw[camada]] #atulizar pesos
    atpeso = np.dot (learnrate / epoch+1,dw[camada])
    weights [camada] += atpeso
    print("pesos dw camada {}: \n{}".format(len(size)-1+camada, dw[camada]))
    print("pesos camada {}: \n{}".format(len(size)-1+camada, weights[camada]))
    print("inputs camada {}: \n{}".format(len(size)-1+camada, wires[camada-1]))
    for camada in range(camada - 1, -len(size), -1): # à partir da penúltima, visto que a última já sofreu a correção
        error_term[camada] = (error_term[camada+1]* weights[camada+1]).T * grads[camada] # err camada oculta

        print("="*(len(size)-1+camada)+">camada {}\ninput : {}\noutput: {}".format(camada + len(size)-1, wires[camada-1],wires[camada]))
       # dw[camada] += error_term[camada]
        print("dwcamada:\n{}".format(dw[camada]))
        print("wires caralho:\n{}".format(wires[camada-1]))
        print("weights caralho:\n{}".format(weights[camada]))
        print("error_term:\n{}".format(error_term))
        e = sum(error_term[camada])
#         print(e)
#        for e,i in zip(error_term[camada],range(len(error_term[camada]))) :
#             dw[camada][i] += np.matrix([e * x for x in wires[camada-1]])
#             dw[camada][i] += e * wires[camada-1].T
        dw[camada] += np.matrix([e * x for x in wires[camada-1]])
        print("dwcamada:\n{}".format(dw[camada]))
        weights[camada] += np.dot (learnrate / epoch+1,dw[camada])
        pass
    yield backward(epoch)

In [42]:
y = [0.2, 0.3] #valor esperado
learnrate = 0.5
weights = originais #pra não dar reset todas as vezes e poder comparar rodadas com mesmos pesos de início
#it = 0
dw = [np.matrix(np.zeros((x,y))) for x,y in zip(size,size[1:])]
wires = [inputs_] + [0] * (len(size)-1)
error_term = [0] * (len(size)-1)
grads = [0] * (len(size)-1)

epochs = 10
b=barrinha(epochs)
for epoch in range(epochs):
    b.refresh(epoch)
    print("epoch: {}/{} {}".format(epoch + 1,epochs,b))
    print("wires:\n {}".format(wires))
    print("gradientes:\n {}".format(grads))
    print('\n')
    next(foward())
    next(backward(epoch + 1))
    print('='*100+'\n')

epoch: 1/10 [0%----------------------------------------------------]
wires:
 [array([0.1, 0.3, 0.5, 0.2]), 0, 0]
gradientes:
 [0, 0]


>camada:0
input: [0.1 0.3 0.5 0.2]
output: [0.44660607 0.51688642 0.49235951]
gradiente: [0.24714909 0.24971485 0.24994162]
=>camada:1
input: [0.44660607 0.51688642 0.49235951]
output: [0.19969331 0.29277626]
gradiente: [0.15981589 0.20705832]

Back Propagation:
=>camada 1
input : [0.44660607 0.51688642 0.49235951]
output: [0.19969331 0.29277626]
erro saída: [0.00030669 0.00722374]
err_term: 
[4.90131651e-05 1.49573627e-03]
pesos: 
[[-1.34410119  0.16154865]
 [-1.28461633 -0.62986099]
 [-0.25170176 -1.27654772]]
gradiente: 
[0.15981589 0.20705832]

pesos dw camada 1: 
[[2.18895771e-05 6.68004902e-04]
 [2.53342395e-05 7.73125771e-04]
 [2.41320981e-05 7.36439982e-04]]
pesos camada 1: 
[[-1.34406836  0.16255066]
 [-1.28457833 -0.6287013 ]
 [-0.25166556 -1.27544306]]
inputs camada 1: 
[0.44660607 0.51688642 0.49235951]
>camada 0
input : [0.1 0.3 0.5 0.2]
ou